### ISSUE TITLE
Изменить имя default сектора

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender_stalker_tools_addon#9]
При импорте level импортёр устанавливает одинаковые имена для секторов. Нужно, чтобы default сектор имел отличное имя, например `sector_default`.

**Comment by PavelBlend** [comment]
Теперь имя дефолтного сектора будет `sector_default`.

**Comment by IgeNiaI** [comment]
@PavelBlend не работает. Дефолтный сектор не всегда находится в конце. К примеру, в Затоне он третий с конца.

**Comment by PavelBlend** [comment]
Да, в сингл картах от ЗП этот способ не сработал. Зато в ТЧ и в мп картах ЗП работает.
Я изменил алгоритм поиска default сектора. Теперь он ищется по количеству порталов. Дефолтный сектор имеет наибольшее количество порталов, так как соединяет все сектора.

**Comment by IgeNiaI** [comment]
Да, в таком виде сработало. Правда и тут не без багов если вдруг будет два сектора с одинаковым количеством порталов. Но это уже маловероятно.
Спасибо

**Comment by PavelBlend** [comment]
Мне интересно, как движок ЗП определяет default сектор? Или для него нет различия, является ли сектор дефолтным или нет? Просто в формате level не хранится такая информация. Сектора имеют только номер визуала и номера порталов.

**Comment by IgeNiaI** [comment]
Движку ЗП скорей всего безразлично. Это мне нужно для оптимизации уровня перед импортом в UE.
Я сейчас проверил, походу, дефолтным его делает конвертер от бардака. Он при конвертации mp_agroprom написал "selected sector #4 (of 5) as default"

**Comment by PavelBlend** [comment]
Нужно изменить алгоритм поиска default сектора. Искать его на основе bounding box привязанных visuals.
